### ISSUE TITLE
"libOGReactNativeWaveform.a" cannot be found

### ISSUE THREAD

**Issue by victorfang** [juananime/react-native-audiowaveform#11]
"libOGReactNativeWaveform.a" cannot be found.
I'm on Mac OS. all NPM, xcode, etc are up-to-date.

**Comment by juananime** [comment]
Have you tried to link the libraries ? the easiest way is:
react-native link react-native-audiowaveform
Cheers

**Comment by juananime** [comment]
I updated the Example folder with both Android and iOS examples working properly. Please get the reference form them. regards.
