### ISSUE TITLE
Cannot compile the example android app

### ISSUE THREAD

**Issue by tf0054** [juananime/react-native-audiowaveform#13]
Thank you for sharing the module. Its fun!
But unfortunately for making an apk with the latest master banch, I had to have few changes like this.
https://github.com/tf0054/react-native-audiowaveform/commit/e3cd51abb41e7b586420b508279608e86f4d8bf5

And I found the change of parameter name and it needed me to apply the according change to react-native-audiowaveform module pulled from npm repo (v1.0.461)
https://github.com/tf0054/react-native-audiowaveform/commit/e3cd51abb41e7b586420b508279608e86f4d8bf5#diff-ff34929671c373ab095bcafa91bd46d4
> patch -d node_modules/react-native-audiowaveform < react-native-audiowaveform_index_js.diff

Is it possible to add WaveformWrapper.js which is missing? I guess itd the best to sync the example between Android and IOS.

**Comment by juananime** [comment]
Hi dude, I've just added the wrapper file, let me know if that works for you in order to close issue.
Thanks for your feedback mate.

**Comment by TryGennai** [comment]
Thank you for adding the file!

I think the changes I have to apply to make the example work would be few now, but am guessing the change of param name in index.android.js and module's index.js would be still necessary.

waveFormStyle.waveColor -> waveFormStyle.rightWaveColor

Also (it isnt serious, but) waveFormStyle.scrubColor wouldnt be used in java codes.

And they lead me to think like the java codes in the master isnt synced with ios codes at the first place.

Am I right? or you are focusing on ios and havent synced android yet?

**Comment by juananime** [comment]
Hi there, I updated the Example folder with working example... sorry for the delay, hope it works. cheers
