### ISSUE TITLE
Unable to run the example app provided within this repo

### ISSUE THREAD

**Issue by hmaster0** [juananime/react-native-audiowaveform#20]
My react-native and reaxt-cli versions are 0.40.1 and 2.0.1 respectively.
The steps I followed to run the app were as follows:-
- Cloned the repo and switched to the `Example` directory.
- I am using yarn instead of npm and so I ran the `yarn` command to install all dependencies.
- Then I started the packager using the `react-native start` command.
- After packager was ready, I ran the `react-native run-android` command which began with building the app.
- As soon as the building was completed, the app interface is loaded but with an error. Here's a screenshot of the error I received:-
![sampleapp_exception](https://user-images.githubusercontent.com/10733612/29156818-62b05452-7dc1-11e7-805c-884fd32155c0.png)
Please advise on how to proceed ahead. I really have to work with this library.

**Comment by juananime** [comment]
Same issue we comment before. Now it should works. Please test
