### ISSUE TITLE
Couldn't find key rightWaveColor in Dynamic object

### ISSUE THREAD

**Issue by hmaster0** [juananime/react-native-audiowaveform#21]
I built a starter app using react-native init. 
My react-native version is 0.46.1 and react-cli version is 2.0.1.
I added the library via `yarn add react-native-audiowaveform`
Then, I manually linked the library into the starter app using the instructions provided in the readme file.
I then changed the index.android.js file, here's the source of that file :-
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import WaveForm from 'react-native-audiowaveform';

export default class WaveformApp extends Component {
  render() {
    return (
      <View style={styles.container}>
        <WaveForm
          source={require('./a_fusion_in_raag_des.mp3')}
          waveFormStyle={{waveColor:'red', scrubColor:'white'}}>
        </WaveForm>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('WaveformApp', () => WaveformApp);

```
After the building process is successfully completed, it shows this error screen as soon as the app is loaded:-
![waveform_exception](https://user-images.githubusercontent.com/10733612/29157098-e4832288-7dc2-11e7-9b9f-a13a662941a2.png)
Please advise as to how to proceed, thank you.

**Comment by juananime** [comment]
That should be fixed by now. Please test.

**Comment by jayrmotta** [comment]
I'm getting this error running on a Moto G4 Plus but not on a Moto Z2.

Any ideas why?
