### ISSUE TITLE
Deprecation warnings on React Native 0.46.1 due to use of old React API

### ISSUE THREAD

**Issue by hmaster0** [juananime/react-native-audiowaveform#22]
I am using react-native 0.46.1 which uses react 16.0.0-alpha12 and react-cli 2.0.1.
I have just added, manually linked and included the react-native-audiowaveform library into my app.
When the app starts it shows me some deprecations in yellow boxes at the bottom of my app.
Here's a screenshot regarding the same :- 
![image](https://user-images.githubusercontent.com/10733612/29158831-1c8fd23c-7dca-11e7-9b82-772a998a869b.jpg)
Please upgrade the React API used for the library. Thank you

**Comment by juananime** [comment]
Hi hammer. I've just updated the Example package to install the last version of react-native-audiowaweform and the last version of RN. I found a misspelling name vars related with waveFormStyle in the Android project. 
I would say it's working now.
Updated in the NPM as a version 1.0.48
Regards
