### ISSUE TITLE
Is this library being even handled anymore? 

### ISSUE THREAD

**Issue by themakerman** [juananime/react-native-audiowaveform#26]

**Comment by juananime** [comment]
Are you asking something in particular?

**Comment by themakerman** [comment]
@juananime The library is not working anymore for newer RN versions. I was planning to use this on a production app but i am stuck on this since few days. Can you please check out whats the problem. I tried fixing the android code but so far no success.
![audiowaveform error](https://user-images.githubusercontent.com/14818804/30147726-818b37f8-93d2-11e7-95c8-888230546167.png)
