### ISSUE TITLE
it's asking for OGWave

### ISSUE THREAD

**Issue by AreebVohra** [juananime/react-native-audiowaveform#51]
![Screenshot_1566364627](https://user-images.githubusercontent.com/34376767/63404523-02a4ae80-c3fd-11e9-9292-9717dc0d74d2.png)

i followed the installation process but it's not working

**Comment by BenjaminLiCN** [comment]
Exactly the same issue

**Comment by sensoft2207** [comment]
Also getting this issue. any solution? I think it's error due to podspec related. this lib need update.

**Comment by trinhvanminh2009** [comment]
Same issue!

**Comment by RoderikMangrove** [comment]
Having the same issue. Any solution yet?

**Comment by AreebVohra** [comment]
not getting any help from the author.
