### ISSUE TITLE
Any intention on supporting cocoapods, and RN 0.61+?

### ISSUE THREAD

**Issue by doelgonzo** [juananime/react-native-audiowaveform#55]
I would love to use this library for some audio recordings, but when trying to use it with RN 0.61.2, it throws an error on the attempt to import <RCTViewManager.h>. Is there intention to support 0.61+? Also, can a podspec be written to make this a pod that can leverage Autolinking?

**Comment by programminPete** [comment]
🙏 here's to hoping .. would love to use as well
