### ISSUE TITLE
Invalid prop `waveFormStyle.waveColor`

### ISSUE THREAD

**Issue by Darwinium** [juananime/react-native-audiowaveform#9]
Hi! Thanks for your plugin 😇

I've tried to make an example from your Readme:
import WaveForm from 'react-native-audiowaveform';

```
<WaveForm 
    source={require('./path/to/your/file.mp3')}  
    waveFormStyle={{waveColor:'red', scrubColor:'white'}}
>
</WaveForm>
```

But i've got:
```
Warning: Failed prop type: Invalid prop `waveFormStyle.waveColor` of type `number` supplied to `OGWave`, expected `string`.
    in OGWave (created by WaveForm)
    in WaveForm (created by Player)
    in RCTView (created by View)
    in View (created by Player)
    in Player (created by CastsList)
    in RCTView (created by View)
    in View (created by CastsList)
    in CastsList (created by App)
    in App (created by CloudCast)
    in CloudCast
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
```

What I have to do?

**Comment by juananime** [comment]
Thanks Darwinium, can you post exactly how you called waveFormStyle in your code?
It need to be a string color ,like 'red', 'black' or '#545454' ...
Regards,

**Comment by Darwinium** [comment]
The code above the exactly how I used. Except path to file, I changed it

**Comment by Darwinium** [comment]
@juananime https://www.dropbox.com/s/dopledzeywwjtf3/Screenshot%202017-02-23%2011.44.43.png?dl=0

The black place for your component but nothing shows. Btw if I'm adding `autoPlay={true}` I hear the sound but nothing see (waveform).

**Comment by juananime** [comment]
I can see the warning too, yet it doesn't make the app crash. To clean warning level is pending.

**Comment by Darwinium** [comment]
But I didn't see the waveform?

**Comment by juananime** [comment]
is advisable to wrap Waveform in a parent component to manage the states.
`
            <WaveForm style={this.props.style}


                      onPress = {(sender) => this.changestate() }
                      source={this.props.source}
                      stop={this.state.stopAudio? true:false}
                      play={this.state.playAudio? true:false}
                      autoPlay={this.props.autoPlay}
                      waveFormStyle={{waveColor:this.props.waveFormStyle.waveColor,scrubColor:this.props.waveFormStyle.scrubColor}}

            />`

**Comment by juananime** [comment]
Its the background color view same as the waveform view? that might make the waveform invisible...

**Comment by Darwinium** [comment]
Maybe it because when I've installed it I've got this
<img width="759" alt="screenshot 2017-02-23 11 51 21" src="https://cloud.githubusercontent.com/assets/52569/23256287/185ef466-f9bf-11e6-8226-426d26daf5cc.png">

> Its the background color view same as the waveform view? that might make the waveform invisible...
I know but it doesn't 😔

**Comment by Darwinium** [comment]
I did it! The problem was in Parent View. When I deleted it it started to work. Anyway thank you! I have  a lot of plans on your component so see you and have a nice day ☀️

**Comment by juananime** [comment]
you are welcome. glad it works 👍
